config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  resources :articles do
    collection do
      post :upload
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many_attached :images

  class << self
    def image_tag_regex
      /!\[article-image:([a-zA-Z0-9-]+)\]/
    end
  end

  def create_attachments
    blobs.each do |temp_blob|
      images.find_or_create_by!(blob: temp_blob)
    end
  end

  def blobs
    image_tags.map {|signed_id| ActiveStorage::Blob.find_signed(signed_id)}
  end

  def image_tags
    body.scan(self.class.image_tag_regex).flatten
  end
end

app/models/checkout.rb
class Checkout
  def once
    true
  end

  def twice
    true
  end
end

app/models/double_checkout.rb
class DoubleCheckout
  def pr
    true
  end

  def merge
    true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show;
  end

  def new
    @article = Article.new
  end

  def edit;
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      @article.create_attachments
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    if @article.update(article_params)
      @article.create_attachments
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @article.destroy!
    redirect_to articles_url, notice: 'Article was successfully destroyed.'
  end

  def upload
    file = params[:file]
    @blob = ActiveStorage::Blob.create_after_upload!(io: file, filename: file.original_filename)
    render json: {filename: @blob.signed_id}
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end


  def article_params
    params.require(:article).permit(:title, :body, images: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  ActiveStorage::Blob
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  def markdown(text)
    unless @markdown
      renderer = RenderCustomHtml.new
      @markdown = Redcarpet::Markdown.new(renderer)
    end

    @markdown.render(text).html_safe
  end
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true, html: {class: 'article'}) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="field">
      <%= form.label :title, "タイトル" %>
      <%= form.text_field :title, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="field">
      <%= form.label :body, "内容" %>
      <%= form.text_area :body, rows: 10, data: {fileupload_url: upload_articles_path}, class: "form-control" %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit("作成", class:"btn btn-primary") %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="#"><h1>記事編集</h1></a>
  </nav>

  <%= render 'form', article: @article %>

  <%= link_to 'Show', @article %> |
  <%= link_to 'Back', articles_path %>
</div>

app/views/articles/index.html.erb
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="#"><h1>記事一覧</h1></a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">

      </ul>
      <form class="form-inline my-2 my-lg-0">
        <%= link_to '新しい記事', new_article_path, class: "btn btn-primary" %>
      </form>
    </div>
  </nav>

  <% if notice.present? %>
    <div class="alert alert-warning m-3" role="alert">
      <%= notice %>
    </div>
  <% end %>

  <% if @articles.present? %>
    <% @articles.each_slice(2) do |articles| %>
      <div class="mt-2 mb-2">
        <div class="row">
          <% articles.each do |article| %>
            <div class="col-sm-6">
              <div class="card">
                <h5 class="card-header"><%= article.title %></h5>
                <div class="card-body">
                  <p class="card-text"><%= markdown(article.body) %></p>
                  <%= link_to 'Show', article, class: "btn btn-primary" %>
                  <%= link_to 'Edit', edit_article_path(article), class: "btn btn-success" %>
                  <%= link_to 'Destroy', article, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger" %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/articles/new.html.erb
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="#"><h1>新しい記事</h1></a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">

      </ul>
      <form class="form-inline my-2 my-lg-0">
        <%= link_to '新しい記事', new_article_path, class: "btn btn-primary" %>
      </form>
    </div>
  </nav>

  <%= render 'form', article: @article %>

  <%= link_to 'Back', articles_path %>
</div>

app/views/articles/show.html.erb
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="#"><h1>記事詳細</h1></a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">

      </ul>
      <form class="form-inline my-2 my-lg-0">
        <%= link_to '新しい記事', new_article_path, class: "btn btn-primary" %>
      </form>
    </div>
  </nav>

  <% if notice.present? %>
    <div class="alert alert-warning m-3" role="alert">
      <%= notice %>
    </div>
  <% end %>

  <div class="mt-2">
    <div class="card">
      <h5 class="card-header"><%= @article.title %></h5>
      <div class="card-body">
        <p class="card-text"><%= markdown(@article.body) %></p>
      </div>
    </div>
  </div>

  <%= link_to 'Edit', edit_article_path(@article) %> |
  <%= link_to 'Back', articles_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StmnStudy4th</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>